name: preview
on:
  workflow_call:
    inputs:
      publish:
        description: 'The directory to publish to pkg.pr.new'
        default: "./packages/**"
        required: false
        type: string
      template:
        description: 'The directory of templates to publish to StackBlitz'
        default: "./examples/**"
        required: false
        type: string
    secrets:
      BOT_APP_ID:
        description: 'The GitHub App ID for authenticating with the GitHub API'
        required: false
      BOT_PRIVATE_KEY:
        description: 'The GitHub App Private Key for authenticating with the GitHub API'
        required: false

jobs:
  preview:
    if: github.repository_owner == 'bombshell-dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Publish Preview
        run: pnpx pkg-pr-new publish '${{inputs.publish}}' --template '${{inputs.template}}'
