name: build
on:
  workflow_call:
    inputs:
      command:
        type: 'string'
        description: 'The name of the package.json script to run'
        required: true
    secrets:
      BOT_APP_ID:
        description: 'The GitHub App ID for authenticating with the GitHub API'
        required: true
      BOT_PRIVATE_KEY:
        description: 'The GitHub App Private Key for authenticating with the GitHub API'
        required: true

jobs:
  build:
    if: github.repository_owner == 'bombshell-dev'
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: bot-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.bot-token.outputs.token }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run "${{env.COMMAND}}"
        env:
          COMMAND: ${{ inputs.command }}
