name: run
on:
  workflow_call:
    inputs:
      commands:
        type: 'string'
        description: |
          A JSON array of package.json scripts, e.g.
          '["lint","test","types"]'
        required: true
    secrets:
      BOT_APP_ID:
        description: 'The GitHub App ID for authenticating with the GitHub API'
        required: false
      BOT_PRIVATE_KEY:
        description: 'The GitHub App Private Key for authenticating with the GitHub API'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ${{ fromJson(inputs.commands) }}

    steps:
      # Check if we have secrets
      - name: Check secrets availability
        id: check-secrets
        run: |
          if [ -n "${{ secrets.BOT_APP_ID }}" ] && [ -n "${{ secrets.BOT_PRIVATE_KEY }}" ]; then
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          fi

      # Generate token only if secrets are available
      - name: Generate a token
        if: steps.check-secrets.outputs.has_secrets == 'true'
        id: bot-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # Checkout with token if available
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.bot-token.outputs.token || '' }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run ${{ matrix.command }}
        run: pnpm run "${{env.COMMAND}}"
        env:
          COMMAND: ${{ matrix.command }}
