name: run
on:
  workflow_call:
    inputs:
      commands:
        type: 'string'
        description: |
          A JSON array of package.json scripts, e.g.
          '["lint","test","types"]'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ${{ fromJson(inputs.commands) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run ${{ matrix.command }}
        run: pnpm run "${{env.COMMAND}}"
        env:
          COMMAND: ${{ matrix.command }}
